"""Daily topic discussion note model."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone, date as date_type

from sqlalchemy import String, Text, Integer, DateTime, Date, ForeignKey, Boolean
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


def _utcnow():
    return datetime.now(timezone.utc)


class DailyNote(Base):
    """A daily topic discussion note generated by EduPilot for a class."""
    __tablename__ = "daily_notes"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    teacher_course_assignment_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("teacher_course_assignments.id"), nullable=False
    )
    teacher_id: Mapped[str] = mapped_column(String(36), ForeignKey("teachers.id"), nullable=False)
    date: Mapped[date_type] = mapped_column(Date, nullable=False)
    topic: Mapped[str] = mapped_column(String(300), nullable=False)
    content: Mapped[str | None] = mapped_column(Text, nullable=True)  # Full markdown content
    key_concepts: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON array
    discussion_points: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON array
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    practice_questions: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON array
    references: Mapped[str | None] = mapped_column(Text, nullable=True)  # JSON array
    duration_minutes: Mapped[int] = mapped_column(Integer, default=60)
    is_ai_generated: Mapped[bool] = mapped_column(Boolean, default=True)
    is_shared: Mapped[bool] = mapped_column(Boolean, default=False)
    shared_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    status: Mapped[str] = mapped_column(String(20), default="draft")  # draft, published, shared
    created_at: Mapped[datetime] = mapped_column(DateTime, default=_utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=_utcnow, onupdate=_utcnow)
