"""Daily Notes routes — generate, list, share topic discussion notes."""

from __future__ import annotations

import json
from datetime import date, datetime, timezone

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel
from pymongo.database import Database

from app.api.deps import get_current_teacher
from app.core.database import get_db
from app.core.exceptions import http_403, http_404
from app.models.communication import new_communication
from app.models.daily_note import new_daily_note
from app.models.document import new_document
from app.models.student import student_full_name

router = APIRouter()


class GenerateNoteRequest(BaseModel):
    class_id: str
    topic: str
    duration_minutes: int = 60
    additional_context: str | None = None


class ShareNoteRequest(BaseModel):
    note_id: str
    class_id: str


def _generate_note_content(topic: str, course_name: str, duration: int, context: str | None) -> dict:
    """Generate structured discussion notes for a topic."""
    key_concepts = [
        f"Core fundamentals of {topic}",
        f"Key principles and definitions in {topic}",
        f"Real-world applications of {topic}",
        f"Common misconceptions about {topic}",
        f"Relationship between {topic} and related concepts",
    ]

    discussion_points = [
        f"What are the primary characteristics of {topic}?",
        f"How does {topic} relate to previous topics covered in {course_name}?",
        f"What are the practical applications of {topic} in industry?",
        f"Compare and contrast different approaches to {topic}.",
        f"What challenges are commonly faced when implementing {topic}?",
    ]

    content = f"""# {topic} — Discussion Notes

## Course: {course_name}
## Duration: {duration} minutes

---

## 📝 Topic Overview

{topic} is a fundamental concept in {course_name}. This discussion note covers the key aspects discussed during today's lecture session.

## 🎯 Learning Objectives

After this session, students should be able to:
1. Understand the core principles of {topic}
2. Identify key components and their relationships
3. Apply concepts of {topic} to solve practical problems
4. Analyze real-world scenarios involving {topic}
5. Evaluate different approaches and methodologies

## 📚 Key Concepts

### 1. Introduction to {topic}
{topic} forms an essential part of {course_name}. Understanding this concept is crucial for building a strong foundation in the subject.

### 2. Core Principles
- **Principle 1**: The fundamental building blocks of {topic}
- **Principle 2**: How {topic} integrates with broader system design
- **Principle 3**: Performance considerations and trade-offs

### 3. Detailed Analysis
The detailed study of {topic} involves understanding both theoretical foundations and practical implementations. Students should focus on:
- Mathematical foundations where applicable
- Algorithm design and analysis
- Implementation strategies
- Testing and validation approaches

### 4. Practical Applications
{topic} has numerous applications in:
- Software development and engineering
- System design and architecture
- Data processing and analysis
- Research and innovation

## 💬 Discussion Points

1. {discussion_points[0]}
2. {discussion_points[1]}
3. {discussion_points[2]}
4. {discussion_points[3]}
5. {discussion_points[4]}

## ✅ Summary

Today's discussion on **{topic}** covered the fundamental concepts, principles, and applications. Students are encouraged to review these notes and explore additional resources for deeper understanding.

## 📝 Practice Questions

1. Define {topic} and explain its significance in {course_name}.
2. List and explain the key components of {topic}.
3. Describe a real-world application of {topic} with an example.
4. Compare different approaches to implementing {topic}.
5. What are the challenges and limitations associated with {topic}?

## 📖 References & Further Reading

- Course textbook chapters related to {topic}
- Online resources and documentation
- Research papers and publications on {topic}
- Video lectures and tutorials

---

*Generated by EduPilot AI Platform*
*{course_name} | {datetime.now().strftime('%B %d, %Y')}*
"""

    if context:
        content = content.replace(
            "## 📝 Topic Overview",
            f"## 📝 Topic Overview\n\n**Instructor's Additional Context:** {context}\n"
        )

    summary = (
        f"Today's lecture covered {topic} in {course_name}. "
        f"Key areas include fundamental principles, practical applications, "
        f"and implementation strategies. Students should review the practice "
        f"questions and discussion points for exam preparation."
    )

    practice_questions = [
        f"Define {topic} and explain its significance in {course_name}.",
        f"List and explain the key components of {topic}.",
        f"Describe a real-world application of {topic} with an example.",
        f"Compare different approaches to implementing {topic}.",
        f"What are the challenges and limitations associated with {topic}?",
    ]

    return {
        "content": content,
        "key_concepts": key_concepts,
        "discussion_points": discussion_points,
        "summary": summary,
        "practice_questions": practice_questions,
    }


@router.post("/generate")
def generate_note(
    body: GenerateNoteRequest,
    teacher: dict = Depends(get_current_teacher),
    db: Database = Depends(get_db),
):
    """Generate a daily topic discussion note for a class."""
    tca = db.teacher_course_assignments.find_one({
        "id": body.class_id, "teacher_id": teacher["id"],
    })
    if not tca:
        raise http_403("Not authorized for this class")

    course = db.courses.find_one({"id": tca["course_id"]})
    course_name = course["name"] if course else "Unknown Course"

    generated = _generate_note_content(
        body.topic, course_name, body.duration_minutes, body.additional_context
    )

    note = new_daily_note(
        teacher_course_assignment_id=body.class_id,
        teacher_id=teacher["id"],
        date=date.today().isoformat(),
        topic=body.topic,
        content=generated["content"],
        key_concepts=json.dumps(generated["key_concepts"]),
        discussion_points=json.dumps(generated["discussion_points"]),
        summary=generated["summary"],
        practice_questions=json.dumps(generated["practice_questions"]),
        duration_minutes=body.duration_minutes,
        is_ai_generated=True,
        status="published",
    )
    db.daily_notes.insert_one(note)

    # Save to Document Studio
    doc = new_document(
        teacher_course_assignment_id=body.class_id,
        teacher_id=teacher["id"],
        title=f"Lecture Notes — {body.topic}",
        document_type="notes",
        format="pdf",
    )
    db.documents.insert_one(doc)

    year = db.years.find_one({"id": tca["year_id"]})
    section = db.sections.find_one({"id": tca["section_id"]})

    return {
        "id": note["id"],
        "topic": note["topic"],
        "content": note["content"],
        "key_concepts": json.loads(note["key_concepts"]) if note.get("key_concepts") else [],
        "discussion_points": json.loads(note["discussion_points"]) if note.get("discussion_points") else [],
        "summary": note["summary"],
        "practice_questions": json.loads(note["practice_questions"]) if note.get("practice_questions") else [],
        "course_name": course_name,
        "course_code": course["code"] if course else "",
        "year_label": year["label"] if year else "",
        "section_name": section["name"] if section else "",
        "date": note["date"],
        "duration_minutes": note["duration_minutes"],
        "is_shared": note.get("is_shared", False),
        "status": note["status"],
        "created_at": note["created_at"].isoformat() if hasattr(note.get("created_at"), 'isoformat') else note.get("created_at"),
    }


@router.get("")
def list_notes(
    class_id: str | None = Query(None),
    note_date: str | None = Query(None),
    teacher: dict = Depends(get_current_teacher),
    db: Database = Depends(get_db),
):
    """List daily notes for the teacher."""
    query_filter = {"teacher_id": teacher["id"]}
    if class_id:
        query_filter["teacher_course_assignment_id"] = class_id
    if note_date:
        query_filter["date"] = note_date

    notes = list(
        db.daily_notes.find(query_filter).sort("created_at", -1).limit(50)
    )

    result = []
    for note in notes:
        tca = db.teacher_course_assignments.find_one(
            {"id": note["teacher_course_assignment_id"]}
        )
        course = db.courses.find_one({"id": tca["course_id"]}) if tca else None
        year = db.years.find_one({"id": tca["year_id"]}) if tca else None
        section = db.sections.find_one({"id": tca["section_id"]}) if tca else None

        shared_at = note.get("shared_at")
        created_at = note.get("created_at")
        result.append({
            "id": note["id"],
            "topic": note["topic"],
            "summary": note.get("summary"),
            "content": note.get("content"),
            "key_concepts": json.loads(note["key_concepts"]) if note.get("key_concepts") else [],
            "discussion_points": json.loads(note["discussion_points"]) if note.get("discussion_points") else [],
            "practice_questions": json.loads(note["practice_questions"]) if note.get("practice_questions") else [],
            "course_name": course["name"] if course else "",
            "course_code": course["code"] if course else "",
            "year_label": year["label"] if year else "",
            "section_name": section["name"] if section else "",
            "date": note["date"],
            "duration_minutes": note.get("duration_minutes", 60),
            "is_shared": note.get("is_shared", False),
            "shared_at": shared_at.isoformat() if hasattr(shared_at, 'isoformat') else shared_at,
            "status": note.get("status", "draft"),
            "created_at": created_at.isoformat() if hasattr(created_at, 'isoformat') else created_at,
        })

    return result


@router.get("/{note_id}")
def get_note(
    note_id: str,
    teacher: dict = Depends(get_current_teacher),
    db: Database = Depends(get_db),
):
    """Get a specific daily note."""
    note = db.daily_notes.find_one({"id": note_id})
    if not note:
        raise http_404("Note not found")
    if note["teacher_id"] != teacher["id"]:
        raise http_403("Not authorized")

    tca = db.teacher_course_assignments.find_one({"id": note["teacher_course_assignment_id"]})
    course = db.courses.find_one({"id": tca["course_id"]}) if tca else None
    year = db.years.find_one({"id": tca["year_id"]}) if tca else None
    section = db.sections.find_one({"id": tca["section_id"]}) if tca else None

    shared_at = note.get("shared_at")
    created_at = note.get("created_at")
    return {
        "id": note["id"],
        "topic": note["topic"],
        "content": note.get("content"),
        "key_concepts": json.loads(note["key_concepts"]) if note.get("key_concepts") else [],
        "discussion_points": json.loads(note["discussion_points"]) if note.get("discussion_points") else [],
        "summary": note.get("summary"),
        "practice_questions": json.loads(note["practice_questions"]) if note.get("practice_questions") else [],
        "course_name": course["name"] if course else "",
        "course_code": course["code"] if course else "",
        "year_label": year["label"] if year else "",
        "section_name": section["name"] if section else "",
        "date": note["date"],
        "duration_minutes": note.get("duration_minutes", 60),
        "is_shared": note.get("is_shared", False),
        "shared_at": shared_at.isoformat() if hasattr(shared_at, 'isoformat') else shared_at,
        "status": note.get("status", "draft"),
        "created_at": created_at.isoformat() if hasattr(created_at, 'isoformat') else created_at,
    }


@router.post("/share")
def share_note_to_class(
    body: ShareNoteRequest,
    teacher: dict = Depends(get_current_teacher),
    db: Database = Depends(get_db),
):
    """Share a daily note to all students in a class via email (demo)."""
    note = db.daily_notes.find_one({"id": body.note_id})
    if not note:
        raise http_404("Note not found")
    if note["teacher_id"] != teacher["id"]:
        raise http_403("Not authorized")

    tca = db.teacher_course_assignments.find_one({
        "id": body.class_id, "teacher_id": teacher["id"],
    })
    if not tca:
        raise http_403("Not authorized for this class")

    students = list(
        db.students.find({"section_id": tca["section_id"], "is_active": True})
        .sort("roll_number", 1)
    )

    course = db.courses.find_one({"id": tca["course_id"]})
    course_name = course["name"] if course else "Course"
    course_code = course["code"] if course else ""

    recipients = [
        {"student_id": s["id"], "email": s["email"], "name": student_full_name(s), "status": "sent"}
        for s in students
    ]

    comm = new_communication(
        teacher_id=teacher["id"],
        teacher_course_assignment_id=body.class_id,
        comm_type="email",
        template_type="daily_notes",
        subject=f"[{course_code}] Discussion Notes: {note['topic']}",
        body=f"Dear Student,\n\nPlease find attached the discussion notes for today's lecture on \"{note['topic']}\" in {course_name}.\n\nKey Topics Covered:\n{note.get('summary', '')}\n\nPlease review these notes and come prepared with questions for the next class.\n\nBest regards,\n{teacher['first_name']} {teacher['last_name']}\n{teacher.get('designation', '')}\nEduPilot Academic Platform",
        recipients=json.dumps(recipients),
        total_recipients=len(students),
        sent_count=len(students),
        status="sent",
        sent_at=datetime.now(timezone.utc),
    )
    db.communications.insert_one(comm)

    # Mark note as shared
    db.daily_notes.update_one(
        {"id": body.note_id},
        {"$set": {
            "is_shared": True,
            "shared_at": datetime.now(timezone.utc),
            "status": "shared",
        }},
    )

    return {
        "success": True,
        "message": f"Notes shared with {len(students)} students via email",
        "total_recipients": len(students),
        "communication_id": comm["id"],
        "student_emails": [s["email"] for s in students],
    }


@router.delete("/{note_id}")
def delete_daily_note(
    note_id: str,
    teacher: dict = Depends(get_current_teacher),
    db: Database = Depends(get_db),
):
    """Delete a daily note and automatically cascade delete its document from Document Studio."""
    note = db.daily_notes.find_one({"id": note_id, "teacher_id": teacher["id"]})
    if not note:
        raise http_404("Daily note not found")

    topic = note.get("topic", "")
    db.daily_notes.delete_one({"id": note_id})

    # Cascade deletion from Document Studio (db.documents)
    if topic:
        db.documents.delete_many({
            "teacher_id": teacher["id"],
            "$or": [
                {"title": {"$regex": topic[:12], "$options": "i"}},
            ],
        })

    return {"success": True, "message": "Daily note and associated studio document deleted successfully"}
