"""Daily Notes routes — generate, list, share topic discussion notes."""

from __future__ import annotations

import json
import uuid
from datetime import date, datetime, timezone

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.api.deps import get_current_teacher
from app.core.exceptions import http_403, http_404
from app.models.teacher import Teacher
from app.models.student import Student
from app.models.enrollment import TeacherCourseAssignment
from app.models.academic import Year, Section, Course
from app.models.daily_note import DailyNote
from app.models.communication import Communication

router = APIRouter()


class GenerateNoteRequest(BaseModel):
    class_id: str
    topic: str
    duration_minutes: int = 60
    additional_context: str | None = None


class ShareNoteRequest(BaseModel):
    note_id: str
    class_id: str


def _generate_note_content(topic: str, course_name: str, duration: int, context: str | None) -> dict:
    """Generate structured discussion notes for a topic (template-based, LLM-upgradable)."""
    key_concepts = [
        f"Core fundamentals of {topic}",
        f"Key principles and definitions in {topic}",
        f"Real-world applications of {topic}",
        f"Common misconceptions about {topic}",
        f"Relationship between {topic} and related concepts",
    ]

    discussion_points = [
        f"What are the primary characteristics of {topic}?",
        f"How does {topic} relate to previous topics covered in {course_name}?",
        f"What are the practical applications of {topic} in industry?",
        f"Compare and contrast different approaches to {topic}.",
        f"What challenges are commonly faced when implementing {topic}?",
    ]

    content = f"""# {topic} — Discussion Notes

## Course: {course_name}
## Duration: {duration} minutes

---

## 📝 Topic Overview

{topic} is a fundamental concept in {course_name}. This discussion note covers the key aspects discussed during today's lecture session.

## 🎯 Learning Objectives

After this session, students should be able to:
1. Understand the core principles of {topic}
2. Identify key components and their relationships
3. Apply concepts of {topic} to solve practical problems
4. Analyze real-world scenarios involving {topic}
5. Evaluate different approaches and methodologies

## 📚 Key Concepts

### 1. Introduction to {topic}
{topic} forms an essential part of {course_name}. Understanding this concept is crucial for building a strong foundation in the subject.

### 2. Core Principles
- **Principle 1**: The fundamental building blocks of {topic}
- **Principle 2**: How {topic} integrates with broader system design
- **Principle 3**: Performance considerations and trade-offs

### 3. Detailed Analysis
The detailed study of {topic} involves understanding both theoretical foundations and practical implementations. Students should focus on:
- Mathematical foundations where applicable
- Algorithm design and analysis
- Implementation strategies
- Testing and validation approaches

### 4. Practical Applications
{topic} has numerous applications in:
- Software development and engineering
- System design and architecture
- Data processing and analysis
- Research and innovation

## 💬 Discussion Points

1. {discussion_points[0]}
2. {discussion_points[1]}
3. {discussion_points[2]}
4. {discussion_points[3]}
5. {discussion_points[4]}

## ✅ Summary

Today's discussion on **{topic}** covered the fundamental concepts, principles, and applications. Students are encouraged to review these notes and explore additional resources for deeper understanding.

## 📝 Practice Questions

1. Define {topic} and explain its significance in {course_name}.
2. List and explain the key components of {topic}.
3. Describe a real-world application of {topic} with an example.
4. Compare different approaches to implementing {topic}.
5. What are the challenges and limitations associated with {topic}?

## 📖 References & Further Reading

- Course textbook chapters related to {topic}
- Online resources and documentation
- Research papers and publications on {topic}
- Video lectures and tutorials

---

*Generated by EduPilot AI — Adamas University*
*{course_name} | {datetime.now().strftime('%B %d, %Y')}*
"""

    if context:
        content = content.replace(
            "## 📝 Topic Overview",
            f"## 📝 Topic Overview\n\n**Instructor's Additional Context:** {context}\n"
        )

    summary = (
        f"Today's lecture covered {topic} in {course_name}. "
        f"Key areas include fundamental principles, practical applications, "
        f"and implementation strategies. Students should review the practice "
        f"questions and discussion points for exam preparation."
    )

    practice_questions = [
        f"Define {topic} and explain its significance in {course_name}.",
        f"List and explain the key components of {topic}.",
        f"Describe a real-world application of {topic} with an example.",
        f"Compare different approaches to implementing {topic}.",
        f"What are the challenges and limitations associated with {topic}?",
    ]

    return {
        "content": content,
        "key_concepts": key_concepts,
        "discussion_points": discussion_points,
        "summary": summary,
        "practice_questions": practice_questions,
    }


@router.post("/generate")
def generate_note(
    body: GenerateNoteRequest,
    teacher: Teacher = Depends(get_current_teacher),
    db: Session = Depends(get_db),
):
    """Generate a daily topic discussion note for a class."""
    tca = db.query(TeacherCourseAssignment).filter(
        TeacherCourseAssignment.id == body.class_id,
        TeacherCourseAssignment.teacher_id == teacher.id,
    ).first()
    if not tca:
        raise http_403("Not authorized for this class")

    course = db.query(Course).filter(Course.id == tca.course_id).first()
    course_name = course.name if course else "Unknown Course"

    generated = _generate_note_content(
        body.topic, course_name, body.duration_minutes, body.additional_context
    )

    note = DailyNote(
        id=str(uuid.uuid4()),
        teacher_course_assignment_id=body.class_id,
        teacher_id=teacher.id,
        date=date.today(),
        topic=body.topic,
        content=generated["content"],
        key_concepts=json.dumps(generated["key_concepts"]),
        discussion_points=json.dumps(generated["discussion_points"]),
        summary=generated["summary"],
        practice_questions=json.dumps(generated["practice_questions"]),
        duration_minutes=body.duration_minutes,
        is_ai_generated=True,
        status="published",
    )
    db.add(note)

    # Save to Document Studio Vault for this class
    from app.models.document import Document
    doc = Document(
        id=str(uuid.uuid4()),
        teacher_course_assignment_id=body.class_id,
        teacher_id=teacher.id,
        title=f"Lecture Notes — {body.topic}",
        document_type="notes",
        format="pdf",
    )
    db.add(doc)

    db.commit()
    db.refresh(note)


    year = db.query(Year).filter(Year.id == tca.year_id).first()
    section = db.query(Section).filter(Section.id == tca.section_id).first()

    return {
        "id": note.id,
        "topic": note.topic,
        "content": note.content,
        "key_concepts": json.loads(note.key_concepts) if note.key_concepts else [],
        "discussion_points": json.loads(note.discussion_points) if note.discussion_points else [],
        "summary": note.summary,
        "practice_questions": json.loads(note.practice_questions) if note.practice_questions else [],
        "course_name": course_name,
        "course_code": course.code if course else "",
        "year_label": year.label if year else "",
        "section_name": section.name if section else "",
        "date": note.date.isoformat(),
        "duration_minutes": note.duration_minutes,
        "is_shared": note.is_shared,
        "status": note.status,
        "created_at": note.created_at.isoformat() if note.created_at else None,
    }


@router.get("")
def list_notes(
    class_id: str | None = Query(None),
    note_date: str | None = Query(None),
    teacher: Teacher = Depends(get_current_teacher),
    db: Session = Depends(get_db),
):
    """List daily notes for the teacher, optionally filtered by class and date."""
    query = db.query(DailyNote).filter(DailyNote.teacher_id == teacher.id)

    if class_id:
        query = query.filter(DailyNote.teacher_course_assignment_id == class_id)

    if note_date:
        try:
            d = date.fromisoformat(note_date)
            query = query.filter(DailyNote.date == d)
        except ValueError:
            pass

    notes = query.order_by(DailyNote.created_at.desc()).limit(50).all()

    result = []
    for note in notes:
        tca = db.query(TeacherCourseAssignment).filter(
            TeacherCourseAssignment.id == note.teacher_course_assignment_id
        ).first()
        course = db.query(Course).filter(Course.id == tca.course_id).first() if tca else None
        year = db.query(Year).filter(Year.id == tca.year_id).first() if tca else None
        section = db.query(Section).filter(Section.id == tca.section_id).first() if tca else None

        result.append({
            "id": note.id,
            "topic": note.topic,
            "summary": note.summary,
            "content": note.content,
            "key_concepts": json.loads(note.key_concepts) if note.key_concepts else [],
            "discussion_points": json.loads(note.discussion_points) if note.discussion_points else [],
            "practice_questions": json.loads(note.practice_questions) if note.practice_questions else [],
            "course_name": course.name if course else "",
            "course_code": course.code if course else "",
            "year_label": year.label if year else "",
            "section_name": section.name if section else "",
            "date": note.date.isoformat(),
            "duration_minutes": note.duration_minutes,
            "is_shared": note.is_shared,
            "shared_at": note.shared_at.isoformat() if note.shared_at else None,
            "status": note.status,
            "created_at": note.created_at.isoformat() if note.created_at else None,
        })

    return result


@router.get("/{note_id}")
def get_note(
    note_id: str,
    teacher: Teacher = Depends(get_current_teacher),
    db: Session = Depends(get_db),
):
    """Get a specific daily note."""
    note = db.query(DailyNote).filter(DailyNote.id == note_id).first()
    if not note:
        raise http_404("Note not found")
    if note.teacher_id != teacher.id:
        raise http_403("Not authorized")

    tca = db.query(TeacherCourseAssignment).filter(
        TeacherCourseAssignment.id == note.teacher_course_assignment_id
    ).first()
    course = db.query(Course).filter(Course.id == tca.course_id).first() if tca else None
    year = db.query(Year).filter(Year.id == tca.year_id).first() if tca else None
    section = db.query(Section).filter(Section.id == tca.section_id).first() if tca else None

    return {
        "id": note.id,
        "topic": note.topic,
        "content": note.content,
        "key_concepts": json.loads(note.key_concepts) if note.key_concepts else [],
        "discussion_points": json.loads(note.discussion_points) if note.discussion_points else [],
        "summary": note.summary,
        "practice_questions": json.loads(note.practice_questions) if note.practice_questions else [],
        "course_name": course.name if course else "",
        "course_code": course.code if course else "",
        "year_label": year.label if year else "",
        "section_name": section.name if section else "",
        "date": note.date.isoformat(),
        "duration_minutes": note.duration_minutes,
        "is_shared": note.is_shared,
        "shared_at": note.shared_at.isoformat() if note.shared_at else None,
        "status": note.status,
        "created_at": note.created_at.isoformat() if note.created_at else None,
    }


@router.post("/share")
def share_note_to_class(
    body: ShareNoteRequest,
    teacher: Teacher = Depends(get_current_teacher),
    db: Session = Depends(get_db),
):
    """Share a daily note to all students in a class via email (demo)."""
    note = db.query(DailyNote).filter(DailyNote.id == body.note_id).first()
    if not note:
        raise http_404("Note not found")
    if note.teacher_id != teacher.id:
        raise http_403("Not authorized")

    tca = db.query(TeacherCourseAssignment).filter(
        TeacherCourseAssignment.id == body.class_id,
        TeacherCourseAssignment.teacher_id == teacher.id,
    ).first()
    if not tca:
        raise http_403("Not authorized for this class")

    # Get all students in the class section
    students = (
        db.query(Student)
        .filter(Student.section_id == tca.section_id, Student.is_active == True)
        .order_by(Student.roll_number)
        .all()
    )

    course = db.query(Course).filter(Course.id == tca.course_id).first()
    course_name = course.name if course else "Course"
    course_code = course.code if course else ""

    # Create communication record
    recipients = [
        {"student_id": s.id, "email": s.email, "name": s.full_name, "status": "sent"}
        for s in students
    ]

    comm = Communication(
        id=str(uuid.uuid4()),
        teacher_id=teacher.id,
        teacher_course_assignment_id=body.class_id,
        comm_type="email",
        template_type="daily_notes",
        subject=f"[{course_code}] Discussion Notes: {note.topic}",
        body=f"Dear Student,\n\nPlease find attached the discussion notes for today's lecture on \"{note.topic}\" in {course_name}.\n\nKey Topics Covered:\n{note.summary}\n\nPlease review these notes and come prepared with questions for the next class.\n\nBest regards,\n{teacher.first_name} {teacher.last_name}\n{teacher.designation}\nAdamas University",
        recipients=json.dumps(recipients),
        total_recipients=len(students),
        sent_count=len(students),
        status="sent",
        sent_at=datetime.now(timezone.utc),
    )
    db.add(comm)

    # Mark note as shared
    note.is_shared = True
    note.shared_at = datetime.now(timezone.utc)
    note.status = "shared"

    db.commit()

    return {
        "success": True,
        "message": f"Notes shared with {len(students)} students via email",
        "total_recipients": len(students),
        "communication_id": comm.id,
        "student_emails": [s.email for s in students],
    }
