"""720 unique Indian student names — curated, realistic, diverse.

Mix of Bengali, Hindi, Tamil, Telugu, Malayalam, Kannada, Marathi, Punjabi,
Gujarati, and other regional name traditions common across Indian universities.
"""

# (first_name, last_name) tuples — all 720 combinations are unique
STUDENT_NAMES: list[tuple[str, str]] = [
    # ---- Section batch 1 (1st Year A: 1-60) ----
    ("Aarav", "Sharma"), ("Aditi", "Banerjee"), ("Akash", "Mukherjee"), ("Ananya", "Das"),
    ("Arjun", "Ghosh"), ("Bhavya", "Chatterjee"), ("Chaitanya", "Sen"), ("Deepak", "Roy"),
    ("Diya", "Bose"), ("Eshan", "Dutta"), ("Fatima", "Khan"), ("Gaurav", "Mondal"),
    ("Harsh", "Sinha"), ("Isha", "Chakraborty"), ("Jatin", "Pal"), ("Kavya", "Sarkar"),
    ("Krishna", "Gupta"), ("Lavanya", "Majumdar"), ("Manish", "Nag"), ("Meera", "Biswas"),
    ("Nakul", "Bhattacharya"), ("Nandini", "Ganguly"), ("Ojas", "Mitra"), ("Pallavi", "Barua"),
    ("Pranav", "Kar"), ("Priya", "Dey"), ("Rahul", "Hazra"), ("Riya", "Samanta"),
    ("Rohan", "Kundu"), ("Sanya", "Choudhury"), ("Samir", "Maity"), ("Shreya", "Ghosh"),
    ("Siddharth", "Adhikari"), ("Sneha", "Haldar"), ("Tarun", "Bag"), ("Trisha", "Paul"),
    ("Uday", "Bera"), ("Varun", "Nandy"), ("Vidya", "Mandal"), ("Vivek", "Saha"),
    ("Yash", "Rajput"), ("Zara", "Ahmed"), ("Aditya", "Goswami"), ("Anjali", "Patel"),
    ("Arnav", "Joshi"), ("Avni", "Thakur"), ("Biplab", "Sarma"), ("Chandni", "Kapoor"),
    ("Daksh", "Malhotra"), ("Devika", "Nair"), ("Dhruv", "Pillai"), ("Ekta", "Reddy"),
    ("Farhan", "Hussain"), ("Gargi", "Basu"), ("Hemant", "Verma"), ("Indira", "Saxena"),
    ("Ishaan", "Tiwari"), ("Juhi", "Rawat"), ("Kartik", "Mishra"), ("Lata", "Chauhan"),

    # ---- Section batch 2 (1st Year B: 61-120) ----
    ("Mahesh", "Deshmukh"), ("Namrata", "Patil"), ("Om", "Kulkarni"), ("Pooja", "Jain"),
    ("Rajesh", "Agarwal"), ("Sakshi", "Pandey"), ("Tanmay", "Dubey"), ("Uma", "Rastogi"),
    ("Vinay", "Dwivedi"), ("Wasim", "Siddiqui"), ("Aadhira", "Menon"), ("Aakash", "Iyer"),
    ("Abhinav", "Krishnan"), ("Amrita", "Subramaniam"), ("Aniket", "Narayanan"), ("Bhumi", "Rajan"),
    ("Chirag", "Venkatesh"), ("Divya", "Sundaram"), ("Eshwar", "Raghavan"), ("Falguni", "Trivedi"),
    ("Girish", "Bhatt"), ("Hema", "Vyas"), ("Ira", "Modi"), ("Jayant", "Mehta"),
    ("Kamal", "Shah"), ("Latika", "Desai"), ("Milan", "Parekh"), ("Nirmala", "Rana"),
    ("Omkar", "Bhonsle"), ("Padma", "Shinde"), ("Radha", "More"), ("Sachin", "Jadhav"),
    ("Tanvi", "Gaikwad"), ("Ujjwal", "Chavan"), ("Vaishnavi", "Sawant"), ("Yashika", "Naik"),
    ("Adarsh", "Singh"), ("Anushka", "Yadav"), ("Aryan", "Kumar"), ("Bhargav", "Prasad"),
    ("Chaitra", "Hegde"), ("Deepika", "Shetty"), ("Esha", "Kamath"), ("Faisal", "Shaikh"),
    ("Gauri", "Pai"), ("Harini", "Rao"), ("Indu", "Gowda"), ("Jayesh", "Bhat"),
    ("Kiran", "Ballal"), ("Lakshmi", "Acharya"), ("Manoj", "Upadhyay"), ("Neha", "Tripathi"),
    ("Omesh", "Srivastava"), ("Pankaj", "Bajpai"), ("Reena", "Awasthi"), ("Suresh", "Khanna"),
    ("Tanya", "Grover"), ("Uditi", "Arora"), ("Vikram", "Batra"), ("Yamini", "Sodhi"),

    # ---- Section batch 3 (1st Year C: 121-180) ----
    ("Alok", "Mathur"), ("Bani", "Purohit"), ("Chandan", "Shukla"), ("Damini", "Tomar"),
    ("Eklavya", "Chahal"), ("Falak", "Gill"), ("Govind", "Dhillon"), ("Hridya", "Kaur"),
    ("Inder", "Bedi"), ("Jasmine", "Sandhu"), ("Kabir", "Bajwa"), ("Lakshmipati", "Sethi"),
    ("Mohit", "Kohli"), ("Navya", "Anand"), ("Param", "Chawla"), ("Rhea", "Vohra"),
    ("Sahil", "Oberoi"), ("Tamanna", "Walia"), ("Umesh", "Tandon"), ("Vrinda", "Suri"),
    ("Amar", "Luthra"), ("Bhavana", "Khurana"), ("Cyrus", "Mistry"), ("Dhanush", "Raman"),
    ("Eva", "Fernandes"), ("Fenil", "D'Souza"), ("Geetanjali", "Rodrigues"), ("Hrishikesh", "Pereira"),
    ("Irfan", "Pinto"), ("Jhanvi", "Lobo"), ("Kushal", "Shenoy"), ("Lina", "Sequeira"),
    ("Manav", "Rebello"), ("Naira", "Cardoz"), ("Oscar", "Gomes"), ("Parvathi", "Nambiar"),
    ("Raman", "Warrier"), ("Smriti", "Panicker"), ("Tejas", "Kurup"), ("Urvi", "Soman"),
    ("Vimal", "Varghese"), ("Wriddhiman", "Chakrabarti"), ("Abhay", "Mahajan"), ("Brinda", "Kelkar"),
    ("Chitra", "Deshpande"), ("Devesh", "Gadkari"), ("Eknath", "Phadke"), ("Gayatri", "Jog"),
    ("Harish", "Gokhale"), ("Iti", "Sathe"), ("Jayashree", "Ranade"), ("Keshav", "Apte"),
    ("Leena", "Limaye"), ("Madhav", "Chitale"), ("Nayan", "Phadnis"), ("Omkar", "Lele"),
    ("Pushpa", "Bapat"), ("Ritesh", "Wagh"), ("Swara", "Kulkarni"), ("Tushar", "Karnik"),

    # ---- Section batch 4 (2nd Year A: 181-240) ----
    ("Achyut", "Mohanty"), ("Barsha", "Panda"), ("Chinmay", "Sahoo"), ("Debashish", "Mishra"),
    ("Ektara", "Nayak"), ("Gyanesh", "Dash"), ("Hema", "Behera"), ("Itishree", "Parida"),
    ("Jyotirmay", "Pradhan"), ("Kamala", "Mohapatra"), ("Lingaraj", "Swain"), ("Madhusmita", "Jena"),
    ("Nibedita", "Rout"), ("Omm", "Pattanaik"), ("Priyaranjan", "Barik"), ("Rashmi", "Sahu"),
    ("Saumya", "Lenka"), ("Tapas", "Senapati"), ("Usha", "Tripathy"), ("Veda", "Satpathy"),
    ("Abir", "Chowdhury"), ("Basundhara", "Dasgupta"), ("Chandrima", "Mukhopadhyay"), ("Debargha", "Bandopadhyay"),
    ("Eshani", "Raychaudhuri"), ("Farjana", "Khatun"), ("Gaurab", "Lahiri"), ("Hemangini", "Sanyal"),
    ("Indrajit", "Sengupta"), ("Janaki", "Bhowmick"), ("Koushik", "Chattopadhyay"), ("Laboni", "Dhar"),
    ("Mrinmoy", "Bhattacharyya"), ("Nabaneeta", "Ghoshal"), ("Oishik", "Roychoudhury"), ("Paromita", "Bhaduri"),
    ("Ranodeep", "Dastidar"), ("Shampa", "Halder"), ("Tithi", "Poddar"), ("Utsav", "Chaudhuri"),
    ("Adrija", "Boral"), ("Bodhisatva", "Chanda"), ("Chandrashekhar", "Mookerjee"), ("Durba", "Ghose"),
    ("Ekadashi", "Maitreya"), ("Firoza", "Begum"), ("Gitanjali", "Ghosal"), ("Himadri", "Neogi"),
    ("Indranil", "Thakurta"), ("Jinia", "Aich"), ("Koustav", "Datta"), ("Lopamudra", "Guha"),
    ("Manas", "Mallick"), ("Nilanjana", "Rakshit"), ("Olivia", "Bose"), ("Pratyush", "Maitra"),
    ("Raima", "Tagore"), ("Supriyo", "Banerjee"), ("Tathagata", "Ganguli"), ("Upasana", "Deb"),

    # ---- Section batch 5 (2nd Year B: 241-300) ----
    ("Avinash", "Murthy"), ("Bhavani", "Reddy"), ("Chakravarthi", "Naidu"), ("Divyanshu", "Ranga"),
    ("Eswar", "Prasad"), ("Gowri", "Lakshmi"), ("Hari", "Varma"), ("Indumathi", "Kota"),
    ("Jagannadh", "Challagulla"), ("Karuna", "Tadepalli"), ("Lalitha", "Maddala"), ("Mohan", "Gandham"),
    ("Niharika", "Vemula"), ("Pavan", "Boyapati"), ("Revathi", "Mudunuri"), ("Srikar", "Polisetty"),
    ("Teja", "Koduri"), ("Uthara", "Sistla"), ("Vasudev", "Ramineni"), ("Yamuna", "Cherukuri"),
    ("Akhil", "Nanda"), ("Bina", "Satapathy"), ("Chetan", "Hegde"), ("Darshana", "Kamat"),
    ("Elango", "Selvan"), ("Fathima", "Bashir"), ("Gautam", "Thapar"), ("Heena", "Bakhshi"),
    ("Ishan", "Chandra"), ("Jaya", "Krishnamurthy"), ("Karthikeyan", "Suresh"), ("Likhith", "Babu"),
    ("Mugdha", "Godbole"), ("Nagarjun", "Swamy"), ("Oviya", "Thangaraj"), ("Prithvi", "Ranganathan"),
    ("Raghu", "Natarajan"), ("Shalini", "Viswanathan"), ("Thiagarajan", "Balakrishnan"), ("Uttam", "Dravid"),
    ("Vijaya", "Tendulkar"), ("Anand", "Laxman"), ("Bhoomi", "Parikh"), ("Chandrakant", "Pandya"),
    ("Dipti", "Raval"), ("Eshaan", "Mody"), ("Falgun", "Jani"), ("Geet", "Contractor"),
    ("Harsh", "Vora"), ("Ila", "Sheth"), ("Jagdish", "Sanghvi"), ("Kaumudi", "Dalal"),
    ("Lalit", "Thakkar"), ("Mitali", "Bhagat"), ("Neel", "Kothari"), ("Palak", "Davda"),
    ("Rashi", "Gajjar"), ("Sagar", "Doshi"), ("Tarini", "Zaveri"), ("Urmila", "Panchal"),

    # ---- Section batch 6 (2nd Year C: 301-360) ----
    ("Vihaan", "Chaube"), ("Arunima", "Rawat"), ("Brijesh", "Negi"), ("Charu", "Bisht"),
    ("Darpan", "Joshi"), ("Eshita", "Pant"), ("Faizan", "Malik"), ("Gagandeep", "Garg"),
    ("Himanshi", "Mittal"), ("Inder", "Aggarwal"), ("Jubin", "Goyal"), ("Kashvi", "Singla"),
    ("Laksh", "Bansal"), ("Mansi", "Wadhwa"), ("Nikhil", "Trehan"), ("Ovais", "Farooqi"),
    ("Pihu", "Saini"), ("Raghav", "Taneja"), ("Saanvi", "Chadha"), ("Tanishq", "Dhawan"),
    ("Udayan", "Bhandari"), ("Varsha", "Jha"), ("Wahid", "Raza"), ("Aadya", "Jaiswal"),
    ("Bhupesh", "Pandey"), ("Chhavi", "Chaturvedi"), ("Diksha", "Pathak"), ("Ekagra", "Nigam"),
    ("Firoz", "Akhtar"), ("Gunjan", "Dixit"), ("Hitesh", "Purwar"), ("Inayat", "Zaidi"),
    ("Janvi", "Kaushik"), ("Kabeer", "Soni"), ("Lajja", "Bhargava"), ("Mrinal", "Shrivastava"),
    ("Naman", "Khandelwal"), ("Ojaswi", "Goswami"), ("Pranjal", "Saxena"), ("Ritika", "Agrawal"),
    ("Shanaya", "Kapoor"), ("Tirth", "Prajapati"), ("Urjita", "Parmar"), ("Vedan", "Solanki"),
    ("Yuvraj", "Rajput"), ("Zoya", "Ansari"), ("Abhinandan", "Chand"), ("Bhairavi", "Bhonsle"),
    ("Chirantan", "More"), ("Devyani", "Maheshwari"), ("Eesha", "Gupta"), ("Fateh", "Singh"),
    ("Garvit", "Meena"), ("Hemani", "Jat"), ("Ishwar", "Rathore"), ("Juhi", "Shekhawat"),
    ("Kaashvi", "Bhati"), ("Lavish", "Dhaka"), ("Mishka", "Parewa"), ("Nihaal", "Bohra"),

    # ---- Section batch 7 (3rd Year A: 361-420) ----
    ("Param", "Sharma"), ("Quasar", "Pillai"), ("Ritwik", "Ghosh"), ("Samridhi", "Das"),
    ("Tanay", "Bose"), ("Urvashi", "Dutta"), ("Vedant", "Sinha"), ("Wafa", "Ahmed"),
    ("Yukta", "Mukherjee"), ("Zeeshan", "Khan"), ("Abhijit", "Roy"), ("Bornali", "Chakraborty"),
    ("Chiranjib", "Pal"), ("Deb", "Sarkar"), ("Eesha", "Majumdar"), ("Firoj", "Mondal"),
    ("Garima", "Nag"), ("Hridaan", "Biswas"), ("Ishika", "Bhattacharya"), ("Jishnu", "Ganguly"),
    ("Kalyan", "Mitra"), ("Lila", "Barua"), ("Monojit", "Kar"), ("Nishtha", "Dey"),
    ("Ojas", "Hazra"), ("Prakrit", "Samanta"), ("Rajanya", "Kundu"), ("Sohini", "Choudhury"),
    ("Turjo", "Maity"), ("Upama", "Sarma"), ("Vaibhav", "Adhikari"), ("Xena", "Haldar"),
    ("Yugantar", "Bag"), ("Zara", "Paul"), ("Abha", "Bera"), ("Bhaskar", "Nandy"),
    ("Chitrangada", "Mandal"), ("Darshan", "Saha"), ("Elan", "Goswami"), ("Firdaus", "Patel"),
    ("Gaurangi", "Joshi"), ("Himani", "Thakur"), ("Irfana", "Kapoor"), ("Jivitesh", "Malhotra"),
    ("Kashish", "Nair"), ("Lilavati", "Reddy"), ("Mithun", "Hussain"), ("Nabanita", "Basu"),
    ("Omisha", "Verma"), ("Prashasti", "Tiwari"), ("Raunak", "Rawat"), ("Soumya", "Mishra"),
    ("Tamal", "Chauhan"), ("Unmesh", "Deshmukh"), ("Vanya", "Patil"), ("Wrik", "Kulkarni"),
    ("Yajnaseni", "Jain"), ("Zubair", "Agarwal"), ("Anumita", "Pandey"), ("Bidisha", "Dubey"),

    # ---- Section batch 8 (3rd Year B: 421-480) ----
    ("Chandrani", "Rastogi"), ("Debjani", "Dwivedi"), ("Ekaansh", "Siddiqui"), ("Fardeen", "Menon"),
    ("Gopa", "Iyer"), ("Harsita", "Krishnan"), ("Ipsita", "Subramaniam"), ("Jagannath", "Narayanan"),
    ("Kakali", "Rajan"), ("Lopa", "Venkatesh"), ("Mainak", "Sundaram"), ("Nabamita", "Raghavan"),
    ("Oindri", "Trivedi"), ("Pritha", "Bhatt"), ("Rittik", "Vyas"), ("Subhodip", "Modi"),
    ("Titir", "Mehta"), ("Uddalak", "Shah"), ("Vrishti", "Desai"), ("Arindam", "Parekh"),
    ("Banhi", "Rana"), ("Chhandak", "Bhonsle"), ("Debjyoti", "Shinde"), ("Esha", "Jadhav"),
    ("Farhan", "Gaikwad"), ("Gulshan", "Chavan"), ("Hirak", "Sawant"), ("Ipsitaa", "Naik"),
    ("Joy", "Singh"), ("Keya", "Yadav"), ("Lipi", "Kumar"), ("Mriganka", "Prasad"),
    ("Neel", "Hegde"), ("Oshin", "Shetty"), ("Pragyaan", "Kamath"), ("Rumi", "Shaikh"),
    ("Shambhavi", "Pai"), ("Turyansh", "Rao"), ("Ujjaini", "Gowda"), ("Viyom", "Bhat"),
    ("Ahana", "Ballal"), ("Bodhi", "Acharya"), ("Chitralekha", "Upadhyay"), ("Dev", "Tripathi"),
    ("Elina", "Srivastava"), ("Firoj", "Bajpai"), ("Gaurika", "Awasthi"), ("Hemraj", "Khanna"),
    ("Ilina", "Grover"), ("Jayanta", "Arora"), ("Kamakshi", "Batra"), ("Lekhraj", "Sodhi"),
    ("Madhumita", "Mathur"), ("Nayantara", "Purohit"), ("Oishani", "Shukla"), ("Poulomi", "Tomar"),
    ("Ranit", "Chahal"), ("Subarna", "Gill"), ("Tirthankar", "Dhillon"), ("Usri", "Kaur"),

    # ---- Section batch 9 (3rd Year C: 481-540) ----
    ("Vaidik", "Bedi"), ("Aheli", "Sandhu"), ("Bhaswar", "Bajwa"), ("Chandreyee", "Sethi"),
    ("Debdoot", "Kohli"), ("Enakshi", "Anand"), ("Farida", "Chawla"), ("Gourab", "Vohra"),
    ("Hritik", "Oberoi"), ("Indrani", "Walia"), ("Josna", "Tandon"), ("Kuhu", "Suri"),
    ("Labanya", "Luthra"), ("Mihir", "Khurana"), ("Nandita", "Mistry"), ("Oindrila", "Raman"),
    ("Parimal", "Fernandes"), ("Rupsa", "D'Souza"), ("Sayantan", "Rodrigues"), ("Tapasi", "Pereira"),
    ("Upamanya", "Pinto"), ("Vasundhara", "Lobo"), ("Adrish", "Shenoy"), ("Barnita", "Sequeira"),
    ("Chandrabhaga", "Rebello"), ("Dibyendu", "Cardoz"), ("Ekta", "Gomes"), ("Fulki", "Nambiar"),
    ("Gandharv", "Warrier"), ("Hansika", "Panicker"), ("Indulekha", "Kurup"), ("Jhelum", "Soman"),
    ("Krishnandu", "Varghese"), ("Lopita", "Mohanty"), ("Moubani", "Panda"), ("Niladri", "Sahoo"),
    ("Ojaswin", "Mishra"), ("Payel", "Nayak"), ("Rimjhim", "Dash"), ("Sannidhya", "Behera"),
    ("Triyama", "Parida"), ("Udayan", "Pradhan"), ("Vineet", "Mohapatra"), ("Aahana", "Swain"),
    ("Bikram", "Jena"), ("Chaya", "Rout"), ("Dharitri", "Pattanaik"), ("Ekram", "Barik"),
    ("Fulki", "Sahu"), ("Gitika", "Lenka"), ("Hemanta", "Senapati"), ("Indulata", "Tripathy"),
    ("Jyotiprakash", "Satpathy"), ("Kanchan", "Chowdhury"), ("Lopita", "Dasgupta"), ("Monideep", "Mukhopadhyay"),
    ("Nibha", "Bandopadhyay"), ("Ojal", "Raychaudhuri"), ("Preetam", "Khatun"), ("Ruchira", "Lahiri"),

    # ---- Section batch 10 (4th Year A: 541-600) ----
    ("Sabyasachi", "Sanyal"), ("Truptimayee", "Sengupta"), ("Utkarsh", "Bhowmick"),
    ("Viraj", "Chattopadhyay"), ("Anwesha", "Dhar"), ("Bratin", "Ghoshal"),
    ("Chandrashekhar", "Roychoudhury"), ("Debasree", "Bhaduri"), ("Ekayan", "Dastidar"),
    ("Freny", "Halder"), ("Gyanranjan", "Poddar"), ("Hrithika", "Chaudhuri"),
    ("Indrasish", "Boral"), ("Jayita", "Chanda"), ("Kunal", "Mookerjee"),
    ("Lagnajita", "Ghose"), ("Madhurima", "Maitreya"), ("Nairiti", "Begum"),
    ("Oishee", "Neogi"), ("Pranjali", "Thakurta"), ("Raiyan", "Aich"),
    ("Souradeep", "Datta"), ("Turni", "Guha"), ("Utpalini", "Mallick"),
    ("Vedanshi", "Rakshit"), ("Archisha", "Maitra"), ("Baibhav", "Tagore"),
    ("Charulata", "Ganguli"), ("Diptendu", "Deb"), ("Eshita", "Chaube"),
    ("Faiza", "Rawat"), ("Gaurish", "Negi"), ("Hritika", "Bisht"),
    ("Iravan", "Pant"), ("Jyotsna", "Malik"), ("Kairav", "Mittal"),
    ("Lavleen", "Aggarwal"), ("Mannat", "Goyal"), ("Nandish", "Singla"),
    ("Ojasvi", "Bansal"), ("Prerit", "Wadhwa"), ("Romit", "Trehan"),
    ("Srestha", "Farooqi"), ("Tavishi", "Saini"), ("Ujjval", "Taneja"),
    ("Viha", "Chadha"), ("Aayat", "Dhawan"), ("Bhrigu", "Bhandari"),
    ("Chayanika", "Jha"), ("Devraj", "Raza"), ("Ektaa", "Jaiswal"),
    ("Falaknaaz", "Chaturvedi"), ("Gunika", "Pathak"), ("Harsh", "Nigam"),
    ("Inaya", "Akhtar"), ("Jinal", "Dixit"), ("Kaushiki", "Purwar"),
    ("Liam", "Zaidi"), ("Meghana", "Kaushik"), ("Nishit", "Soni"),

    # ---- Section batch 11 (4th Year B: 601-660) ----
    ("Ojashwi", "Bhargava"), ("Partha", "Shrivastava"), ("Riddhi", "Khandelwal"),
    ("Saptarshi", "Goswami"), ("Trinetra", "Agrawal"), ("Unnayan", "Prajapati"),
    ("Vartika", "Parmar"), ("Aarini", "Solanki"), ("Bhumika", "Rajput"),
    ("Chaitali", "Ansari"), ("Darshika", "Chand"), ("Elam", "More"),
    ("Freya", "Maheshwari"), ("Gyanada", "Meena"), ("Hemangika", "Jat"),
    ("Inaaya", "Rathore"), ("Jigyasa", "Shekhawat"), ("Kiaan", "Bhati"),
    ("Lekha", "Dhaka"), ("Mridula", "Parewa"), ("Nishka", "Bohra"),
    ("Onir", "Murthy"), ("Priyanshi", "Naidu"), ("Reyansh", "Ranga"),
    ("Shravya", "Lakshmi"), ("Tavish", "Varma"), ("Urja", "Kota"),
    ("Vedika", "Challagulla"), ("Aashi", "Tadepalli"), ("Bhavesh", "Maddala"),
    ("Charvi", "Gandham"), ("Diti", "Vemula"), ("Eshwar", "Boyapati"),
    ("Falak", "Mudunuri"), ("Gatik", "Polisetty"), ("Haritima", "Koduri"),
    ("Ivan", "Sistla"), ("Jivika", "Ramineni"), ("Kyra", "Cherukuri"),
    ("Lohith", "Nanda"), ("Miraya", "Satapathy"), ("Nishant", "Kamat"),
    ("Omaira", "Selvan"), ("Pranati", "Bashir"), ("Rishit", "Thapar"),
    ("Sarthak", "Bakhshi"), ("Taarini", "Chandra"), ("Udbhav", "Krishnamurthy"),
    ("Vanya", "Suresh"), ("Avyaan", "Babu"), ("Bela", "Godbole"),
    ("Chirayu", "Swamy"), ("Dhanvi", "Thangaraj"), ("Eshika", "Ranganathan"),
    ("Farhaad", "Natarajan"), ("Gaatha", "Viswanathan"), ("Hrishi", "Balakrishnan"),
    ("Ihita", "Dravid"), ("Japneet", "Tendulkar"),

    # ---- Section batch 12 (4th Year C: 661-720) ----
    ("Kashvee", "Laxman"), ("Laaibah", "Parikh"), ("Mitansh", "Pandya"),
    ("Nihira", "Raval"), ("Oorja", "Mody"), ("Preesha", "Jani"),
    ("Renesh", "Contractor"), ("Shaurya", "Vora"), ("Tarannum", "Sheth"),
    ("Umang", "Sanghvi"), ("Viaan", "Dalal"), ("Ahaan", "Thakkar"),
    ("Bhoumik", "Bhagat"), ("Chintan", "Kothari"), ("Dakshita", "Davda"),
    ("Eshaal", "Gajjar"), ("Fariya", "Doshi"), ("Gaurang", "Zaveri"),
    ("Heeral", "Panchal"), ("Indrani", "Sharma"), ("Jivin", "Banerjee"),
    ("Kanak", "Mukherjee"), ("Laveena", "Das"), ("Madhur", "Ghosh"),
    ("Nivedita", "Chatterjee"), ("Ovin", "Sen"), ("Prakriti", "Roy"),
    ("Rudr", "Bose"), ("Samhita", "Dutta"), ("Tejal", "Sinha"),
    ("Udita", "Chakraborty"), ("Vivaan", "Pal"), ("Aishani", "Sarkar"),
    ("Bhavit", "Gupta"), ("Cheshta", "Majumdar"), ("Dhairya", "Nag"),
    ("Eshaan", "Biswas"), ("Fiza", "Bhattacharya"), ("Garv", "Ganguly"),
    ("Hiyaa", "Mitra"), ("Ishani", "Barua"), ("Jahaan", "Kar"),
    ("Krishiv", "Dey"), ("Lavanya", "Hazra"), ("Mahira", "Samanta"),
    ("Nyra", "Kundu"), ("Omveer", "Choudhury"), ("Pratiti", "Maity"),
    ("Riyanshi", "Ghosh"), ("Snigdha", "Adhikari"), ("Trishaan", "Haldar"),
    ("Uttara", "Bag"), ("Virat", "Paul"), ("Aarika", "Bera"),
    ("Bhargavi", "Nandy"), ("Chiraag", "Mandal"), ("Divija", "Saha"),
    ("Eshna", "Rajput"), ("Faarih", "Ahmed"), ("Gopal", "Goswami"),
    ("Hrithik", "Patel"),
]

assert len(STUDENT_NAMES) == 720, f"Expected 720 names, got {len(STUDENT_NAMES)}"
# Verify uniqueness
assert len(set(STUDENT_NAMES)) == 720, "Duplicate student names detected!"
