import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * EduPilot AI — Professional PDF Template Generator
 * Uses jsPDF with Adamas University branding
 */

const COLORS = {
  primary: [0, 96, 181] as [number, number, number],     // #0060B5
  secondary: [140, 198, 63] as [number, number, number],  // #8CC63F
  dark: [15, 23, 42] as [number, number, number],         // slate-900
  gray: [100, 116, 139] as [number, number, number],      // slate-500
  light: [241, 245, 249] as [number, number, number],     // slate-100
  white: [255, 255, 255] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
  green: [34, 197, 94] as [number, number, number],
  amber: [245, 158, 11] as [number, number, number],
};

function addHeader(doc: jsPDF, title: string, subtitle: string) {
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Top accent bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 4, 'F');
  doc.setFillColor(...COLORS.secondary);
  doc.rect(0, 4, pageWidth, 2, 'F');

  // University name
  doc.setFontSize(18);
  doc.setFont('times', 'bold');
  doc.setTextColor(...COLORS.primary);
  doc.text('ADAMAS UNIVERSITY', pageWidth / 2, 22, { align: 'center' });

  // Subtitle line
  doc.setFontSize(8);
  doc.setFont('times', 'normal');
  doc.setTextColor(...COLORS.gray);
  doc.text('School of Engineering & Technology • Computer Science & Engineering', pageWidth / 2, 28, { align: 'center' });

  // Divider
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.5);
  doc.line(20, 32, pageWidth - 20, 32);

  // Document title
  doc.setFontSize(14);
  doc.setFont('times', 'bold');
  doc.setTextColor(...COLORS.dark);
  doc.text(title, pageWidth / 2, 42, { align: 'center' });

  // Document subtitle
  if (subtitle) {
    doc.setFontSize(9);
    doc.setFont('times', 'normal');
    doc.setTextColor(...COLORS.gray);
    doc.text(subtitle, pageWidth / 2, 48, { align: 'center' });
  }


  return 54; // Y position after header
}

function addFooter(doc: jsPDF, pageNum?: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const totalPages = doc.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);

    // Bottom accent bar
    doc.setFillColor(...COLORS.primary);
    doc.rect(0, pageHeight - 6, pageWidth, 4, 'F');
    doc.setFillColor(...COLORS.secondary);
    doc.rect(0, pageHeight - 8, pageWidth, 2, 'F');

    // Footer text
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.gray);
    doc.text('Generated by EduPilot AI — Adamas University', 20, pageHeight - 12);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 20, pageHeight - 12, { align: 'right' });
  }
}

function addMetadataBox(doc: jsPDF, y: number, metadata: Record<string, string>) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const boxWidth = pageWidth - 40;
  const entries = Object.entries(metadata);
  const boxHeight = 8 + entries.length * 7;

  doc.setFillColor(...COLORS.light);
  doc.setDrawColor(200, 210, 220);
  doc.roundedRect(20, y, boxWidth, boxHeight, 3, 3, 'FD');

  let currentY = y + 7;
  entries.forEach(([key, value]) => {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.gray);
    doc.text(`${key}:`, 26, currentY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.dark);
    doc.text(value, 80, currentY);
    currentY += 7;
  });

  return y + boxHeight + 6;
}

function addSectionTitle(doc: jsPDF, y: number, title: string, emoji?: string) {
  if (y > doc.internal.pageSize.getHeight() - 40) {
    doc.addPage();
    y = 20;
  }
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.primary);
  const label = emoji ? `${emoji} ${title}` : title;
  doc.text(label, 20, y);
  doc.setDrawColor(...COLORS.secondary);
  doc.setLineWidth(0.3);
  doc.line(20, y + 2, doc.internal.pageSize.getWidth() - 20, y + 2);
  return y + 8;
}

function addParagraph(doc: jsPDF, y: number, text: string, maxWidth?: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const width = maxWidth || pageWidth - 40;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.dark);
  const lines = doc.splitTextToSize(text, width);
  
  for (const line of lines) {
    if (y > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      y = 20;
    }
    doc.text(line, 20, y);
    y += 5;
  }
  return y + 2;
}

function addBulletList(doc: jsPDF, y: number, items: string[]) {
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.dark);
  const pageWidth = doc.internal.pageSize.getWidth();

  for (const item of items) {
    if (y > doc.internal.pageSize.getHeight() - 30) {
      doc.addPage();
      y = 20;
    }
    doc.setFillColor(...COLORS.primary);
    doc.circle(24, y - 1.5, 1.2, 'F');
    const lines = doc.splitTextToSize(item, pageWidth - 50);
    for (const line of lines) {
      doc.text(line, 28, y);
      y += 5;
    }
    y += 1;
  }
  return y + 2;
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// PUBLIC API — PDF GENERATORS
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export interface QuizPDFData {
  title: string;
  courseName: string;
  courseCode: string;
  yearLabel: string;
  sectionName: string;
  teacherName: string;
  topic: string;
  difficulty: string;
  totalMarks: number;
  duration: number;
  questions: Array<{
    number: number;
    text: string;
    type: string;
    options?: string[];
    marks: number;
  }>;
}

export function generateQuizPDF(data: QuizPDFData) {
  const doc = new jsPDF();
  let y = addHeader(doc, data.title, `${data.courseName} (${data.courseCode})`);

  y = addMetadataBox(doc, y, {
    'Course': `${data.courseName} (${data.courseCode})`,
    'Class': `${data.yearLabel} — Section ${data.sectionName}`,
    'Faculty': data.teacherName,
    'Topic': data.topic,
    'Difficulty': data.difficulty.charAt(0).toUpperCase() + data.difficulty.slice(1),
    'Total Marks': String(data.totalMarks),
    'Duration': `${data.duration} minutes`,
    'Date': new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' }),
  });

  // Instructions
  y = addSectionTitle(doc, y, 'Instructions');
  y = addBulletList(doc, y, [
    'Answer all questions. Each question carries the marks indicated.',
    'Write your answers clearly and legibly.',
    'For MCQ questions, select the most appropriate answer.',
    `Total marks: ${data.totalMarks} | Time allowed: ${data.duration} minutes`,
  ]);

  // Questions
  y = addSectionTitle(doc, y, 'Questions');
  for (const q of data.questions) {
    if (y > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = 20;
    }
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.dark);
    const qLabel = `Q${q.number}. [${q.marks} mark${q.marks > 1 ? 's' : ''}]`;
    doc.text(qLabel, 20, y);
    y += 5;
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(q.text, doc.internal.pageSize.getWidth() - 50);
    for (const line of lines) {
      doc.text(line, 26, y);
      y += 5;
    }

    if (q.options && q.options.length > 0) {
      const optLabels = ['(a)', '(b)', '(c)', '(d)'];
      for (let i = 0; i < q.options.length; i++) {
        if (y > doc.internal.pageSize.getHeight() - 30) {
          doc.addPage();
          y = 20;
        }
        doc.setFontSize(8.5);
        doc.text(`    ${optLabels[i]} ${q.options[i]}`, 26, y);
        y += 5;
      }
    }
    y += 4;
  }

  addFooter(doc);
  doc.save(`${data.title.replace(/\s+/g, '_')}.pdf`);
}

export interface AssessmentReportPDFData {
  title: string;
  courseName: string;
  courseCode: string;
  yearLabel: string;
  sectionName: string;
  teacherName: string;
  totalMarks: number;
  results: Array<{
    rollNumber: string;
    studentName: string;
    score: number;
    maxScore: number;
    percentage: number;
    grade: string;
  }>;
}

export function generateAssessmentReportPDF(data: AssessmentReportPDFData) {
  const doc = new jsPDF();
  let y = addHeader(doc, `Assessment Report: ${data.title}`, `${data.courseName} (${data.courseCode})`);

  y = addMetadataBox(doc, y, {
    'Course': `${data.courseName} (${data.courseCode})`,
    'Class': `${data.yearLabel} — Section ${data.sectionName}`,
    'Faculty': data.teacherName,
    'Total Marks': String(data.totalMarks),
    'Total Students': String(data.results.length),
    'Date': new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' }),
  });

  // Summary stats
  const scores = data.results.map(r => r.percentage);
  const avg = scores.length > 0 ? (scores.reduce((a, b) => a + b, 0) / scores.length).toFixed(1) : '0';
  const highest = scores.length > 0 ? Math.max(...scores).toFixed(1) : '0';
  const lowest = scores.length > 0 ? Math.min(...scores).toFixed(1) : '0';
  const passed = data.results.filter(r => r.percentage >= 40).length;

  y = addSectionTitle(doc, y, 'Performance Summary');
  y = addBulletList(doc, y, [
    `Class Average: ${avg}%`,
    `Highest Score: ${highest}%`,
    `Lowest Score: ${lowest}%`,
    `Pass Rate: ${scores.length > 0 ? ((passed / scores.length) * 100).toFixed(1) : 0}% (${passed}/${scores.length})`,
  ]);

  // Results table
  y = addSectionTitle(doc, y, 'Detailed Results');
  autoTable(doc, {
    startY: y,
    head: [['#', 'Roll No', 'Student Name', 'Score', 'Max', '%', 'Grade']],
    body: data.results.map((r, i) => [
      String(i + 1), r.rollNumber, r.studentName,
      String(r.score), String(r.maxScore),
      `${r.percentage}%`, r.grade,
    ]),
    theme: 'grid',
    headStyles: { fillColor: COLORS.primary, fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7.5 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: 20, right: 20 },
    styles: { cellPadding: 3 },
  });

  addFooter(doc);
  doc.save(`Assessment_Report_${data.title.replace(/\s+/g, '_')}.pdf`);
}

export interface DailyNotePDFData {
  topic: string;
  courseName: string;
  courseCode: string;
  yearLabel: string;
  sectionName: string;
  teacherName: string;
  date: string;
  duration: number;
  content: string;
  keyConcepts: string[];
  discussionPoints: string[];
  summary: string;
  practiceQuestions: string[];
}

export function generateDailyNotePDF(data: DailyNotePDFData) {
  const doc = new jsPDF();
  let y = addHeader(doc, `Discussion Notes: ${data.topic}`, `${data.courseName} (${data.courseCode})`);

  y = addMetadataBox(doc, y, {
    'Course': `${data.courseName} (${data.courseCode})`,
    'Class': `${data.yearLabel} — Section ${data.sectionName}`,
    'Faculty': data.teacherName,
    'Topic': data.topic,
    'Duration': `${data.duration} minutes`,
    'Date': data.date,
  });

  // Content / Notes body
  if (data.content) {
    y = addSectionTitle(doc, y, 'Lecture Notes & Discussion Summary');
    // Strip markdown headings for clean PDF text rendering
    const cleanedContent = data.content
      .replace(/^#+\s+/gm, '')
      .replace(/\*\*/g, '')
      .replace(/`/g, '');
    y = addParagraph(doc, y, cleanedContent);
  } else if (data.summary) {
    y = addSectionTitle(doc, y, 'Lecture Notes');
    y = addParagraph(doc, y, data.summary);
  }

  // Key Concepts
  if (data.keyConcepts && data.keyConcepts.length > 0) {
    y = addSectionTitle(doc, y, 'Key Concepts Covered');
    y = addBulletList(doc, y, data.keyConcepts);
  }

  // Discussion Points
  if (data.discussionPoints && data.discussionPoints.length > 0) {
    y = addSectionTitle(doc, y, 'Discussion Points');
    y = addBulletList(doc, y, data.discussionPoints);
  }

  // Practice Questions
  if (data.practiceQuestions && data.practiceQuestions.length > 0) {
    y = addSectionTitle(doc, y, 'Practice Questions');
    data.practiceQuestions.forEach((q, i) => {
      if (y > doc.internal.pageSize.getHeight() - 30) {
        doc.addPage();
        y = 20;
      }
      doc.setFontSize(9);
      doc.setFont('times', 'normal');
      doc.setTextColor(...COLORS.dark);
      const lines = doc.splitTextToSize(`${i + 1}. ${q}`, doc.internal.pageSize.getWidth() - 50);
      for (const line of lines) {
        doc.text(line, 24, y);
        y += 5;
      }
      y += 2;
    });
  }

  addFooter(doc);
  doc.save(`Discussion_Notes_${data.topic.replace(/\s+/g, '_')}.pdf`);
}


export interface ClassReportPDFData {
  courseName: string;
  courseCode: string;
  yearLabel: string;
  sectionName: string;
  teacherName: string;
  students: Array<{
    rollNumber: string;
    name: string;
    email: string;
    attendance: number;
    avgScore: number;
    cgpa: number | null;
    riskLevel: string;
  }>;
}

export function generateClassReportPDF(data: ClassReportPDFData) {
  const doc = new jsPDF('landscape');
  let y = addHeader(doc, `Class Report: ${data.courseName}`, `${data.yearLabel} — Section ${data.sectionName}`);

  y = addMetadataBox(doc, y, {
    'Course': `${data.courseName} (${data.courseCode})`,
    'Class': `${data.yearLabel} — Section ${data.sectionName}`,
    'Faculty': data.teacherName,
    'Total Students': String(data.students.length),
    'Report Date': new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' }),
  });

  autoTable(doc, {
    startY: y,
    head: [['#', 'Roll No', 'Student Name', 'Email', 'Attendance %', 'Avg Score', 'CGPA', 'Risk']],
    body: data.students.map((s, i) => [
      String(i + 1), s.rollNumber, s.name, s.email,
      `${s.attendance}%`, String(s.avgScore),
      s.cgpa ? String(s.cgpa) : 'N/A', s.riskLevel.toUpperCase(),
    ]),
    theme: 'grid',
    headStyles: { fillColor: COLORS.primary, fontSize: 7.5, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: 15, right: 15 },
    styles: { cellPadding: 2.5 },
    didParseCell: (data: any) => {
      if (data.column.index === 7 && data.section === 'body') {
        const val = String(data.cell.raw).toLowerCase();
        if (val === 'high') data.cell.styles.textColor = COLORS.red;
        else if (val === 'medium') data.cell.styles.textColor = COLORS.amber;
        else if (val === 'low') data.cell.styles.textColor = [200, 150, 0];
        else data.cell.styles.textColor = COLORS.green;
      }
    },
  });

  addFooter(doc);
  doc.save(`Class_Report_${data.courseCode}_${data.sectionName}.pdf`);
}
